### ISSUE TITLE
None use of DRY and OOP principles in this repo.

### ISSUE THREAD

**Issue by n-tdi** [MX-boop/HolyPY#1]
Hello @MX-boop, you seem to be missing a lot of object-orientated programming design principles and patterns. You also seem to violate the DONT REPEAT YOURSELF principle in creating multiple variables that do the same thing.

**Comment by MX-boop** [comment]
Thank you for the tip, I would like to consult you in person about what I could have done better. I can full aggre that my code was shit, I orginally had the messages print in many diffrent colors so I created other varibles for color codes but then decided agansit it and changed all the codes to be white. I also tryed to use diffrent libarys for alot of the repitive things(IE: messages, urls, progress bars, colors) but I wanted to make the code work using the base pip packages. Thank you for this comment and I have implement some changes. Thanks.
